### ISSUE TITLE
1D mesh with vertices only has zero weights

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1074]
The following script:
```
import openturns as ot
# Zero weights !
vertices = ot.Sample([0.,0.1,0.2,0.3,0.4,0.5],1)
mesh = ot.Mesh(vertices)
weights = mesh.computeWeights()
print(weights)
```
produces:
``` 
[0,0,0,0,0,0]
``` 

Therefore, the constructor Mesh(vertices) cannot be used. For example, when using the KarhunenLoeveSVDAlgorithm, because zero weights generate an exception (which is correct).

The workaround script is:
```
vertices = ot.Sample([0.,0.1,0.2,0.3,0.4,0.5],1)
npoints = vertices.getSize()
simplices = [[i,i+1] for i in range(npoints-1)]
mesh = ot.Mesh(vertices,simplices)
weights = mesh.computeWeights()
print(weights)
```
which prints:
```
[0.05,0.1,0.1,0.1,0.1,0.05]
```
However, the expected behavior of the unspecified simplices is to "automatically" compute the simplices as in the second example, not to leave empty simplices as in the current implementation.

**Comment by regislebrun** [comment]
@mbaudin47 The way you construct your sample is wrong, or at least not documented. The constructors are either from a 2-d sequence of floats, or from a size and dimension, or from a size and a sequence of floats. The actual issue is the fact that OT lets you build a sample this way with no complaint... and it looks like the resulting sample is valid!
You should write:
```
vertices = ot.Sample([[0.],[0.1],[0.2],[0.3],[0.4],[0.5]])
```
or
```
vertices = ot.Sample([[x] for x in [0.,0.1,0.2,0.3,0.4,0.5]])
```
or
```
vertices = ot.IntervalMesher([6]).build(ot.Interval(0.0, 0.5))
```
The other point is that if you build a mesh with vertices only, there is no topological information and no notion of element, even in 1D. As the weight of a given vertex is computed as the mean value of the volumes of the elements to which it belongs, the weight is zero if there is no simplex.
You expect this constructor to build the simplices automatically, taking into account the natural order. But you may want to have a mesh with no simplex even in 1D, eg to discretize a covariance model for which the topology is useless. So no bug here but a feature: the ability to build a mesh as a set of floating vertices.

or more directly:
```
mesh = ot.IntervalMesher([5]).build(ot.Interval(0.0, 0.5))
weights = mesh.computeWeights()
print(weights)
```
