### ISSUE TITLE
2-d GaussianProcess realization graph regression

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#1160]
The graph of a 2-d GP is just awfuly scaled, was fine before (1.11 maybe, to be confirmed):

![gp](https://user-images.githubusercontent.com/3832365/58828439-bdff4780-8645-11e9-8901-8037a040630b.png)

```
import openturns as ot
from openturns.viewer import View

amplitude = [1.0]*2
scale = [1.0]*2
myCov = ot.ExponentialModel(scale, amplitude)
myMesh = ot.IntervalMesher([10]*2).build(ot.Interval([0.0]*2, [1.0]*2))
myProcess = ot.GaussianProcess(myCov, myMesh)

#realCont = myProcess.getContinuousRealization()
realDisc = myProcess.getRealization()
graph = realDisc.draw()

graph.setTitle('Stationnary Gaussian realization')
graph.setXTitle('e1')
graph.setYTitle('e2')
View(graph).save('/tmp/gp.png')
```

**Comment by regislebrun** [comment]
Try with these two lines at the beginning of your script:
```
ot.ResourceMap.SetAsScalar("Field-ArrowRatio", 0.015)
ot.ResourceMap.SetAsScalar("Field-ArrowScaling", 0.075)
```
The result should look better.

**Comment by jschueller** [comment]
It looks fine, thanks.

Do we want some kind of normalization here ? The code mentions "as we want the same size for all the arrows":
https://github.com/openturns/openturns/blob/135aa59c51d3e4450c297b5f1f2ccabe0b9160af/lib/src/Base/Stat/FieldImplementation.cxx#L395

**Comment by regislebrun** [comment]
The comment is misleading. It should be: "as we want the same ratio for all the arrows". In fact, additional work should be done here in order to get something meaningful even if:
+ the values of the field are large (ie a kind of normalization wrt max ||value||)
+ the size of the domain (already taken into account through vertices.getMin() and vertices.getMax())
+ the density of the vertices (something like the d-root of the vertices number)
Do you want to play around these ideas or do you want me to code something here?

**Comment by jschueller** [comment]
Yes, I'd be happy if you could have a look.

**Comment by regislebrun** [comment]
Sorry I missed your comment for the release! It should be fixed today.

**Comment by regislebrun** [comment]
Done. I don't know how to update the Changelog using the new convention.
