### ISSUE TITLE
unimplemented Mixture::getStandardRepresentative

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#1187]
so Mixture::getStandardMoment is wrong

```
import openturns as ot

ticks=[0,1,3,6]
cpt=[0.6,0.75,0.9]
histogram = ot.Histogram(ticks, cpt)

coll = []
for k in range(len(ticks)-1):
    coll.append(ot.Uniform(ticks[k], ticks[k+1]))
mixture = ot.Mixture(coll, cpt)
for k in range(1,5):
    print('standard moment', k, 'histogram:', histogram.getStandardMoment(k), 'mixture:', mixture.getStandardMoment(k))

standard moment 1 histogram: [-0.133333] mixture: [2.6]
standard moment 2 histogram: [0.37037] mixture: [9.93333]
standard moment 3 histogram: [-0.0851852] mixture: [43.9]
standard moment 4 histogram: [0.232099] mixture: [209]
```

Maybe Mixture::getStandardRepresentative should throw notdefinedexception when the size of the collection is > 1, thoughts ?

**Comment by regislebrun** [comment]
The getStandardRepresentative() method is implemented at the DistributionImplementation level. When there is no linear transformation able to reduce the parameter dimension, the standard representative is taken equal to the distribution itself. Your mixture is an histogram "by chance", because you selected uniform atoms, but in the general case it is not and there is no systematic way to define a standard representation in the general case.

**Comment by jschueller** [comment]
so what about my proposition to throw in Mixture::getStandardRepresentative ?

**Comment by jschueller** [comment]
| If you do that, StandardDistributionPoylnomialFactory will no be able to construct the orthonormal 
| polynomial family of a Mixture. So don't do that!

so at least getStandardMoment should throw

**Comment by regislebrun** [comment]
The point is: what should be a standard representative here? Since this notion has been introduced in OT (in relation with the ModifiedMomentsChebychevAlgorithm, removed since then), the default behaviour has been to consider that any distribution is its own standard representative if no clear linear transformation should act as a parameter reduction device. Then, by definition, the standard moments are the moments of the standard representative. So either you overload getStandardRepresentative() or you keep it as is, but you don't change getStandardMoment(). I don't see clearly what bothers you here? Could you develop a little bit?

**Comment by jschueller** [comment]
It triggered me a bit because it can return a wrong result, as shown in my example.
