### ISSUE TITLE
hmat compression method selection

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#1365]
- HMatrixImplementation::setKey does not handle aca random
- HMatrixImplementation::setKey does not take the same strings as HMatParameters
- I could be a good idea to reuse the same strings as the hmat c++ enum names instead of introducing new ones: 'ACA full' -> 'AcaFull', 'ACA random' -> 'AcaRandom' ...
- Could we default to the aca random compression method in the ResourceMap instead of aca full ?
- I'd prefer the ResourceMap key to use a string instead of an int, it's more explicit

Tell me what do you think, and I'll make the corresponding changes.
cc @poncetr

**Comment by regislebrun** [comment]
Looks good to me. Thanks for taking the charge of the changes. Romain is in holidays for a week, but I can't see why he would disagree. Regarding the way the key is defined, it is an old story. It should have been changed years ago, and it is better to do it now that we have something working instead of waiting for many people writing many scripts and then break everything!
