### ISSUE TITLE
CleaningStrategy should be removed to make the functional chaos simpler

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1394]
There are currently 3 ways to get sparsity in the polynomial chaos. 
* the `LeastSquaresMetaModelSelectionFactory` class is a way to get sparsity from the LARS selection method,
* the `AdaptiveStrategy` class selects the significant coefficients in the decomposition, 
* the last of the 3 ways of creating an enumerate function, the `HyperbolicAnisotropicEnumerateFunction`, is another way of getting sparsity.

Let us focus on the selection methods in `AdaptiveStrategy`. 
* The `FixedStrategy` uses a given number of coefficients. 
* The `SequentialStrategy` uses a method to sequentially select the significant coefficients. 
* Once the coefficients are computed, the `CleaningStrategy` removes coefficients which are, e.g., smaller than a threshold. 

On the other hand, there are two `ProjectionStrategy`. 
* The `IntegrationStrategy` computes the coefficients from quadrature. 
* The `LeastSquaresStrategy` computes the coefficients from quadrature. 

One of the children classes of the `LeastSquaresStrategy` is the `LeastSquaresMetaModelSelectionFactory`, which uses the `LARS` selection procedure.

The most efficient is the `SequentialStrategy`. The `FixedStrategy` algorithm is the naïve one, and cannot be removed. 

The `CleaningStrategy` 
* was chronologically the first to be developed, 
* is less efficient than `SequentialStrategy`, and 
* is never used in practice. 
 
This is why it should be removed from the library.

**Comment by regislebrun** [comment]
I agree with the need to simplify the functional chaos algorithm, but I disagree with the fact that the SequentialStrategy is the most efficient one. I developed the three strategies (FixedStrategy, SequentialStrategy and CleaningStrategy) in 2008, the first one because it is the simplest one, the two others as examples of adaptive selections of functions. The SequentialStrategy is BAD because it only relies on the empirical risk to stop the selection, and as it is a decreasing function os the basis size, it is only a very inefficient way to explore the whole basis. The CleaningStrategy was a more evolved algorithm, allowing to constrain the size and thus the complexity of the meta-model. It should have evolved into a ridge regression strategy but the work has never been completed. On the other hand, LARS has been implemented as a ProjectionStrategy, which is somewhat strange as its role is to select functions into a basis!

In my view we should remove both CleaningStrategy and SequentialStrategy, and replace them by a RidgeStrategy and LARSStrategy.

**Comment by mbaudin47** [comment]
@sofianehaddad suggests to include these changes into a broader regression models architecture.

**Comment by mbaudin47** [comment]
I plan to include this simplification in the 2021 list.

**Comment by mbaudin47** [comment]
After some thinking on this topic, I think that the `CleaningStrategy` is one of the few ways to produce sparsity when we compute the coefficients using integration in the current state of the library. This is showed in the example that I wrote here:

https://openturns.github.io/openturns/latest/auto_meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.html

**Comment by jschueller** [comment]
we agreed to drop SequentialStrategy instead

**Comment by mbaudin47** [comment]
Ok, good.
