### ISSUE TITLE
Python import otagrum throws an error

### ISSUE THREAD

**Issue by laurent101** [openturns/openturns#1403]
Hello, I've built OTAgrum from sources with both OT and aGrUM without any issues. However, when importing otagrum in Python I get the following error:
>>> import otagrum
terminate called after throwing an instance of 'OT::InternalException'
  what():  Key 'JunctionTreeBernsteinCopulaFactory-DefaultAlpha' is missing in ResourceMap as a Scalar.
Aborted

I checked /lib/src/OTAgrumResourceMap.cxx and JunctionTreeBernsteinCopulaFactory-DefaultAlpha is defined with 0.1.

The related C++ test works. Could this be related to Swift? 

Any assistance would be much appreciated.

Thank you

**Comment by laurent101** [comment]
> which distro is it ? debian 10 ?

I use Debian 10

**Comment by laurent101** [comment]
Did the cmake fix in OT you submitted solve the problem in otagrum?

Am I right in assuming that using the latest github versions of openturns and otagrum will solve the problem?

Thank you for your assistance.

**Comment by jschueller** [comment]
the fix is in a branch of my fork, it's not yet in master

**Comment by laurent101** [comment]
No worries. I checked out the cmake fix you submitted, rebuilt otagrum with openturns 1.15dev and the problem was solved.  I ran all otagrum tests and replicated the available Jupyter notebook examples without issues.

Again, thank you for your assistance.

**Comment by regislebrun** [comment]
WARNING! We found a major bug in otagrum due to the fact that agrum identifies variables using names and OT using indices, and the link is done using agrum's IDs, which are unique but not necessary contiguous (which is tested) nor constant (which is NOT tested). As a result, the map between agrum variables and their OT counterpart may be lost. We are working hard to fix it ASAP.
Sorry for that.
