### ISSUE TITLE
Most of the simulation algorithms for rare event fail on a coronavirus example

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1405]
I implemented the SIR disease propagation model in order to study the spread of the MERS-CoV. Once the rare event has been defined, I tried the following algorithms:

- ProbabilitySimulationAlgorithm with MonteCarloExperiment: quite fast, works
- SubsetSampling: never end
- FORM: quick to run, works
- PostAnalyticalImportanceSampling: does not work, generate wrong input for the model
- PostAnalyticalControlledImportanceSampling: does not work, generate wrong input for the model

Here is the test-case:
```
import openturns as ot

def buildFunction(beta, nu, N, t0):
    f = ot.SymbolicFunction(['t', 'S', 'I', 'R'], [str(-beta/N)  + '*S*I', str(beta/N) + 'S*I-' + str(nu) + '*I', str(nu) + '*I'])
    phi = ot.ParametricFunction(f, [0], [t0])
    return phi

def computeMax(X):
    print("X=", ot.Point(X))
    dt = 1.0 / 24.0
    N0 = X[0]
    I0 = X[1]
    betaIni = X[2]
    betaNew = X[3]
    tNew = X[4]
    nu = X[5]
    # First phase, no intervention
    phi = buildFunction(betaIni, nu, N0, 0.0)
    solver = ot.Fehlberg(phi)
    initialState = [N0-I0, I0, 0.0]
    nt = int(tNew / dt) + 1
    dt = tNew / (nt - 1)
    grid = ot.RegularGrid(0.0, dt, nt).getVertices().asPoint()
    result = solver.solve(initialState, grid)
    # Extract the maximum number of infected people in phase 0
    max0 = result.getMax()[1]
    # Second phase, after intervention
    phi = buildFunction(betaNew, nu, N0, tNew)
    solver = ot.Fehlberg(phi)
    initialState = result[-1]
    grid = ot.RegularGrid(tNew, dt, int(300 / dt + 1)).getVertices().asPoint()
    result = solver.solve(initialState, grid)
    # Extract the maximum number of infected people in phase 1
    max1 = result.getMax()[1]
    return [max(max0, max1)]

# Pour FORM
ot.ResourceMap.SetAsUnsignedInteger("OptimizationAlgorithm-DefaultMaximumEvaluationNumber", 10000)
ot.ResourceMap.SetAsUnsignedInteger("OptimizationAlgorithm-DefaultMaximumIterationNumber", 10000)

threshold = 1000

N0 = ot.Uniform(50950000.0, 51050000.0)
I0 = ot.Beta(2.0, 5.0, 1.0, 3.0)
betaIni = ot.Beta(5.5, 5.5, 0.215, 0.248)
betaNew = ot.Gamma(2.8, 2870, 0.0183)
tNew = ot.Uniform(24.0, 29.0)
nu = ot.Gamma(7.3, 975, 0.021)
dist_X = ot.ComposedDistribution([N0, I0, betaIni, betaNew, tNew, nu])
X = ot.RandomVector(dist_X)

f = ot.PythonFunction(6, 1, computeMax)
Y = ot.CompositeRandomVector(f, X)
E = ot.ThresholdEvent(Y, ot.Greater(), threshold)
# Subset locks
print("Subset")
subset = ot.SubsetSampling(E)
subset.run()
# FORM in order to use PostAnalytical methods
print("FORM")
cobyla = ot.Cobyla()
form = ot.FORM(cobyla, E, X.getMean())
form.run()
# First post-analytical algo
print("Post1")
post1 = ot.PostAnalyticalImportanceSampling(form.getResult())
post1.run()
# Second post-analytical algo
print("Post2")
post2 = ot.PostAnalyticalControlledImportanceSampling(form.getResult())
post2.run()
```

**Comment by sofianehaddad** [comment]
@regislebrun one of the bugs is due to https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Algorithm/Simulation/PostAnalyticalImportanceSampling.cxx#L68

In fact in https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Algorithm/Simulation/PostAnalyticalImportanceSampling.cxx#L65 we are sampling in the `standard space` and using the function in `physical space`...

**Comment by jschueller** [comment]
- the fix works for PostAnalyticalImportanceSampling.
- PostAnalyticalControlledImportanceSampling needs the same fix, but I dont trust the result as there is only 1 block (it returns the control probability and the block variance is null), where can I find more infos about the algorithm ?

**Comment by regislebrun** [comment]
The method is described (in French) slides 22 to 24, and there is a benchmark of the methods slides 25 to 30.
[Cours_3_Methodes_specifiques.pdf](https://github.com/openturns/openturns/files/4325932/Cours_3_Methodes_specifiques.pdf)

**Comment by jschueller** [comment]
thanks, I see nothing wrong in PostAnalyticalControlledImportanceSampling then

**Comment by jschueller** [comment]
subset sampling just has a higher outersampling default (1e4)

**Comment by mbaudin47** [comment]
I am not that sure that FORM provides an accurate result here. Indeed, notice that the first parameter has an order of magnitude close to 7. The other parameters have an order of magnitude close to 0 or 1. In this case, the finite difference method used to compute the gradient may not be accurate, because the default differentiation step may not be appropriate. This is particuarily necessary here because of the approximation errors in the ODE solver.

Moreover, the SORM method fails here because some curvatures are negative. I would suggest to configure the differentiation step for both the gradient and the Hessian.
