### ISSUE TITLE
Expected improvement-based EfficientGlobalOptimization stopping criterion could be improved

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1432]
The default ImprovementFactor of the [EfficientGlobalOptimization](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.EfficientGlobalOptimization.html#openturns.EfficientGlobalOptimization.setImprovementFactor) class is set in the [ResourceMap](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.ResourceMap.html?highlight=EfficientGlobalOptimization-DefaultImprovementFactor) to 1.

If I understand correctly, this means that the optimization is stopped unless the expected improvement is at least |Y_min|.
This seems weird.

Thanks @tbittar for bringing this issue to my attention.

Edit: the issue is deeper than that. See @tbittar's comment below.

**Comment by josephmure** [comment]
This issue is related to https://github.com/openturns/openturns/issues/1302#issuecomment-546977914.

**Comment by tbittar** [comment]
In fact, I think the stopping criterion based on the ImprovementFactor may not be robust to a function translation. Let me illustrate what I mean by an example.

Take the example with the EI formulation from http://openturns.github.io/openturns/latest/examples/ego.html?highlight=ego
In this example, we minimize the ackley function that I call `f` in the sequel. EGO makes 5 iterations as expected and stops because of the MaximumEvaluationNumber criterion: this is perfectly fine !

Now, take the same example and translate `f` by 10^6, that is instead of minimizing the function `f`, we are now minimizing the function `g=f+10^6`. Here, EGO only makes one iteration and stops directly because of the ImprovementFactor criterion.

Let me analyze what happened. First, notice that the metamodels for `f` and `g` only differs by the TrendCoefficient which is translated by `10^6`. This is fine.  As the ImprovementFactor is set to 1, EGO stops whenever `max EI < |f_min|` (1st example) or `max EI < |g_min|` (2nd example) where `f_min` and `g_min` are the best observations of `f` and `g` so far. As the metamodels only differ by the TrendCoefficient and have the same CovarianceModel, the EI is the same for both examples. However, EGO stops early for the 2nd example because of a higher value of `g_min`. However, we expect the algorithm to have the same behavior on these two examples.

From my personal experience, a default value of 1 for the ImprovementFactor often makes the algorithm to stop after 1 iteration. 

Could we consider an improvement criterion of the from max EI < |f_min - f_mean| where `f_mean` could be either the mean of the observations of `f` or the mean of the kriging mean over the whole space? Another suggestion could be to look at the variation of `max EI` between two iterations and to stop when the decrease is not sufficient in some sense to be precised.

**Comment by jschueller** [comment]
yes, that criteria is not easy to work with

**Comment by tbittar** [comment]
Yes, I think the usual convergence criteria are enough. At first, setting a default value to 0 seems a good idea as it would prevent the algorithm from stopping earlier than expected by the user.

But, as it is hard to work with this criteria, I think that in the end it should be either improved or removed completely.

**Comment by mbaudin47** [comment]
@tbittar In the PR, I tried to improve the example, which never worked. But I cannot find a setting which make it run more than one iteration. Can you make it work please?

**Comment by jschueller** [comment]
look at the EGO test: it runs several iterations
