### ISSUE TITLE
The Normal().getRoughness() method is wrong.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1485]
The `getRoughness` method of the `Normal` distribution returns a correct result only in 1 dimension. For dimension greater than 1, the result is wrong.

```
dimension = 2
distribution = ot.Normal(dimension)
R = distribution.getRoughness()
```
produces 0.28209479177387814. But the correct result is 0.0795775, with an absolute error lower than 3.e-7. 

This is because the current formula is:
```
wrongR = ot.Point([1.0 / (2.0 * np.sqrt(np.pi))])
```
but the correct formula for a standard normal multivariate gaussian is:
```
exactRforStandardNormal = ot.Point([1.0 / ((2.0 * np.sqrt(np.pi)) ** dimension)])
```
The faulty code is here:

https://github.com/openturns/openturns/blob/38d0aad0f1d0dfcc6db661dba681846630418d7e/lib/src/Uncertainty/Distribution/Normal.cxx#L712

The formula I suggest is only correct for a diagonal covariance (equal to 1!). Generalizing the formula would require further investigation. A way to validate the code is to use the Python prototype provided in #1443, because it works whatever the distribution. A quick "fix" would be to generate a NotImplementedException for non unity dimension.

**Comment by regislebrun** [comment]
This method was added to OT specifically for the KernelSmoothing algorithm, so in an univariate context. Then, it appeared that almost nothing had to be gained from a practical point of view from knowing the roughness of the kernel if one uses a symmetric unimodal kernel (symmetry is mandatory to get the correct order in the AMISE expansion, and unimodality is expected to give more weight to the data point in its own vicinity). As a result it has been implemented only for the symmetric univariate distributions at this time, then it has simply be forgotten, which is bad.

I am not aware of any actual statistical application of the PDF roughness in higher dimension. Do you have such a use-case? Otherwise, I would suggest one of these three options:

1. We simply deprecate this method
2. We limit the implementation to the 1D case
3. We provide a multidimensional implementation, as proposed by Sofiane, but with an additional implementation based on sampling for large dimension, in the spirit of computeEntropy()

**Comment by mbaudin47** [comment]
Here is the context of this bug.

For the theoretical study of the MISE error of the histogram, we need to evaluate the roughness of the distribution:

![image](https://user-images.githubusercontent.com/31351465/82193837-3f52f700-98f6-11ea-9296-0912ff93ae29.png)

(see Scott, "Multivariate density estimation", page 60). Therefore, in order to study the behavior of the MISE error of the univariate histogram applied to the LogNormal distribution, this quantity is required. I have a Notebook example which shows this if you are interested on the topic (actually, I have a bunch of Notebooks!).

For the theoretical study of the AMISE error of univariate kernel smoothing, the rugosity of the kernel is required if the rugosity of the second derivative of f is known:

![image](https://user-images.githubusercontent.com/31351465/82194201-b5eff480-98f6-11ea-90ac-d2cdba6a182a.png)

If the distribution is known, then the rugosity of the second derivative is also required, but this is not provided in the library (so that there cannot be a bug!). Hence, the fact that the generic service is not available (but will soon be, thanks to #1486) already mentionned in #1443 prevents from testing kernels which are not currently available in the lib.

I have not studied multivariate nonparametric methods in depth yet, so I cannot answer on this topic for the moment.

Aside from theoretical study, I do not think that there is much applications requiring multivariate roughness. This is why limiting the current implementation to 1D sounds reasonable to me. Notice that the implementation I suggested in #1443 was based on QMC sampling, while Sofiane's better implementation is based on IteratedQuadrature, an algorithm which will perform better in low dimension. However, since the implementation that Sofiane suggests works, why not using it?

**Comment by sofianehaddad** [comment]
@regislebrun let us go for 3. Then when we have better knowledges/application on the multidimensional usage, we can use sampling for large dimension.

I think using multidimensional kernels like in https://cran.r-project.org/web/packages/ks/ks.pdf could rely on the roughness for efficiency and so.
Otherwise  we might drop (deprecate) the method for dimension > 1 if it has no sense

**Comment by regislebrun** [comment]
Once again, these formulas rely on the AMISE criterion which is by no mean a gold standard. For the multivariate case, there is much more to be gain to allow for non-product kernels than to fine-tune the multiplicative factor, which is essentially 1 if you look at Scott's table 6.2. The PR proposed by Sofiane is ok for me, I only suggested to add a sampling alternative for higher dimensions if we really want to address this case. The DistributionImplementation::computeEntropy() method has such a machinery: GaussKronrod for the 1D case, IteratedQuadrature for the ND case with moderate N, then MC or QMC (depending on the availability of an efficient Rosenblatt transformation) for larger dimensions. BTW, except if you intend to use an histogram as a kernel, there is no need to iterate over the singularity points as any reasonable kernel should have no singularity inside of its support.
In fact, the AMISE expansion assumes that the underlying PDF is twice continuously differentiable, so it looks weird to learn it using non-smooth kernels as at the end you will get a non-smooth PDF. I would have expected to see a comment on this point in Scott's or Wand's books but as far as I remember it is not mentioned in either book.
