### ISSUE TITLE
Wrong formula for Expected Improvement evaluation ?

### ISSUE THREAD

**Issue by tbittar** [openturns/openturns#1495]
In line 96 of ```EfficientGlobalOptimization.cxx```, the Expected Improvement is computed as follows: 
``` Scalar ei = fmMk * DistFunc::pNormal(ratio) + sk * DistFunc::pNormal(ratio);``` where pNormal is the CDF of the normal distribution. 

I think that we should use the PDF of the normal distribution for the term after ```sk```. Is it a bug or did I miss something ?

**Comment by jschueller** [comment]
at least that's not what I wrote in the doc, I'll check.

**Comment by mbaudin47** [comment]
This is here:

https://github.com/openturns/openturns/blob/3c377575eed7170e56246da832734acec52a66a5/lib/src/Uncertainty/Algorithm/Optimization/EfficientGlobalOptimization.cxx#L96

I agree. 
There is no dNormal function, so I suggest to use the Normal class :

```
Normal n();
Scalar ei = fmMk * n.computeCDF(Point(1, ratio)) + sk * n.computePDF(Point(1, ratio));
```

I think that clarity should be favored to performance in this particular case, i.e. avoid using directly the exp() function.

**Comment by mbaudin47** [comment]
Just to see the impact of this bug, we may analyse the equation:

![image](https://user-images.githubusercontent.com/31351465/82658030-a5a58580-9c26-11ea-9da1-7bbd1531f95c.png)

The first part (exploitation) takes into account for the search of a new min, based on the kriging prediction. The second (exploration) takes into account for the kriging variance. Taking Phi instead of phi changes the relative weight of these terms. I expect that the behavior of the algorithm should be very different.

**Comment by sofianehaddad** [comment]
my bad, sorry!
I changed it in 6cde2f5220271f0095a016a21fe81cec2b85d220 and indeed we need a `dNormal` function.
The idea is avoiding the creation of useless `Normal` object which might be heavy
