### ISSUE TITLE
Wrong formula for MauntzKucherenkoSensitivityAlgorithm

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1570]
If I understand the code correctly, the [implemented formula](https://github.com/openturns/openturns/blob/6ef868a09b1baf365ed7b793d23fbbce35ee211d/lib/src/Uncertainty/Algorithm/Sensitivity/MauntzKucherenkoSensitivityAlgorithm.cxx#L106) for the [MauntzKucherenko V_{-i} estimator](https://openturns.github.io/openturns/master/user_manual/_generated/openturns.MauntzKucherenkoSensitivityAlgorithm.html) is:
![Wrong_MauntzKucherenko](https://user-images.githubusercontent.com/31989332/89759424-71858680-daea-11ea-8d85-f7175011560b.png)
where $\tilde{G}$ is the "centered" model, i.e. $\sum_k \tilde{G}(X_k) = 0$.
I think the code is wrong, because it does not match [this technical note](https://openturns.github.io/openturns/papers/RT-PMFRE-01116-001C_-_Rapport_loi_estimateur_sobol.pdf).

@jschueller @mbaudin47 Assuming my understanding is correct, should I propose a fix within PR #1562 or should I create a new PR?

**Comment by jschueller** [comment]
I'm surprised because we validated extensively these estimators, see scripts in validation/src/sobol_estimator_variance

**Comment by sofianehaddad** [comment]
@josephmure I think there is no issue
The doc mention V_{-i} whereas in the code we compute VT_{i} = Var(Y) - V_{-i}

Starting from 
![image](https://user-images.githubusercontent.com/1433220/89924002-adf7d600-dc01-11ea-9fd3-d85fd5cab0b6.png)

we get VT_{i} as mentioned above and we get the formula in the technical note:

![image](https://user-images.githubusercontent.com/1433220/89922151-f1047a00-dbfe-11ea-954c-5e1f58fd917e.png)

Eq (85) is implemented in the API: https://github.com/openturns/openturns/blob/6ef868a09b1baf365ed7b793d23fbbce35ee211d/lib/src/Uncertainty/Algorithm/Sensitivity/MauntzKucherenkoSensitivityAlgorithm.cxx#L106

**Comment by josephmure** [comment]
According to the technical note, the MauntzKucherenko estimator for the Sobol' total index is:


![MauntzKucherenkoTrue](https://user-images.githubusercontent.com/31989332/90023885-8a419800-dcb4-11ea-9082-f4b2394daa14.png)

I believe what is actually implemented is:

![MauntzKucherenkoFalse](https://user-images.githubusercontent.com/31989332/90023989-ae04de00-dcb4-11ea-8496-98e2dd7466cd.png)

**Comment by sofianehaddad** [comment]
@josephmure normalization is done with respect to the variance and not the second order moment

**Comment by josephmure** [comment]
@sofianehaddad I am really confused. For the denominator, I only copied the technical note. Is normalization done differently in the technical note than in the code?

About the red term, I don't think it vanishes. If both of my expressions of $\widehat{ST}_i$ are correct, then
![Consequence](https://user-images.githubusercontent.com/31989332/90118676-e3630780-dd58-11ea-83b1-ba88f5363552.png)

However, we have the following equality:

![VarianceEqualities](https://user-images.githubusercontent.com/31989332/90118751-fd9ce580-dd58-11ea-9f6f-0ede63446af8.png)

So that would imply that \tilde{G} is constant over the whole sample A. That can't be right.

**Comment by sofianehaddad** [comment]
why your expression equals 0? If X is a centered random variable the E(Y) = 0 and E(Y^2) differ from 0
Also the right term equals 0 (N * mean = 0 if mean = 0!)
Notice the normalization is done with respect to the variance of the centered variable both in technical note & code.
Finally the red term vanishes because it as a mean of centered variable...

**Comment by josephmure** [comment]
1) The fact that my expression equals 0 is implied by the assertion that both expressions of $\widehat{ST}_i$ are equal.

2) The red term is not the mean of a centered variable: $\sum_{k=1}^N \tilde{G}(\boldsymbol{A}_k)$ is not equal to 0. [In the code](https://github.com/openturns/openturns/blob/a9bf78671c2d7d193d3a54c67e7c7d8b98fc0c88/lib/src/Uncertainty/Algorithm/Sensitivity/SobolIndicesAlgorithmImplementation.cxx#L953), G is not centered with respect to the sample A, but with respect to the full sample (A, B, E^i where i goes from 1 to the inputDimension):

```
  // center Y
  Point muY(fullOutputDesign.computeMean());
  outputDesign_ = fullOutputDesign - muY;
```

**Comment by sofianehaddad** [comment]
For point 2, I didn't realize changes done some times ago. Previously the red term was only the mean of the so called reference value see https://github.com/openturns/openturns/commit/8c0b9d74a50cae3fbf02318dc48ce07fe9535516#diff-f1c025590b4f14611454a1d12c927bf6L87) and changes implies many things...

For point 3, agreed (as consequence)

For point 1 we have to check due to the two previous points.

We need to discuss all these points soon. Let this issue open

**Comment by jschueller** [comment]
I think me missed this issue today

**Comment by sofianehaddad** [comment]
Indeed. 
IMHO we should first fix the way we center `Y`

**Comment by jschueller** [comment]
I'm marking it as 1.16 just to remember it, but it's not mandatory for the release

**Comment by sofianehaddad** [comment]
@josephmure I think I got it! Issue is in the API doc.

I found the my own notes corresponding to the first implementation of the estimation. One should reads:
![image](https://user-images.githubusercontent.com/1433220/100019774-ed2bea80-2dde-11eb-8a8d-a082b09660bb.png)

Instead of

![image](https://user-images.githubusercontent.com/1433220/100022990-74c82800-2de4-11eb-8e8e-d46b0e4863c3.png)

in [the api documentation](https://openturns.github.io/openturns/master/user_manual/_generated/openturns.MauntzKucherenkoSensitivityAlgorithm.html#openturns.MauntzKucherenkoSensitivityAlgorithm)

In sum, we should replace `V_{-i}` by `VT{i}` and fix the sign!
As discussed early, we use `E[X^2] = Var[X] + E[X]^2` in the code to get the estimator and we get the corresponding one. The implementation was done before adding a global `centring`.

However there is probably some troubles concerning the confidence interval estimate using the `delta method` as the estimator below seems wrong:
![image](https://user-images.githubusercontent.com/1433220/89922151-f1047a00-dbfe-11ea-954c-5e1f58fd917e.png)

Could you please have a look ?

**Comment by josephmure** [comment]
I agree with the fact that the doc is wrong, but I still think the code is wrong too. I need LaTeX to explain why, so I have written a post on the forum: https://openturns.discourse.group/t/mauntz-kucherenko-formula/68
