### ISSUE TITLE
The equation of the Fejer quadrature rule is triplicated

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1590]
The equation of the 3 quadrature rules: 

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.FejerAlgorithm.html

but the equations are the same in the three cases:

![image](https://user-images.githubusercontent.com/31351465/92389951-4ce8f280-f11a-11ea-85ec-4f7cac279292.png)

**Comment by jschueller** [comment]
its the weights that are different for the 3 methods, see: 
https://github.com/openturns/presentation/blob/master/developer/tps/tps.tex#L134
https://github.com/openturns/presentation/blob/master/developer/tps/tps.tex#L158
https://github.com/openturns/presentation/blob/master/developer/tps/tps.tex#L172

**Comment by regislebrun** [comment]
In fact there is a typo in the slides of the developer training. I already mentioned it to Sofiane before his PR was merged, and we agreed to fix it after the merge, but unfortunately it is stuck in my laptop. A reliable reference is here:
https://en.wikipedia.org/wiki/Clenshaw%E2%80%93Curtis_quadrature
and we read that the points are (almost) the same for Clenshaw Curtis and Fejer2 (where the two endpoints are removed), and are different for Fejer1, which uses the zeros of the Chebychev polynomials instead of their maxima.
