### ISSUE TITLE
The TrapezoidalFactory freezes Cobyla

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1614]
The notebook estimate_multivariate_distribution.ipynb freezes on the parameter estimation of the `TrapezoidalFactory`. To avoid this, the following workaround has been implemented:

https://github.com/openturns/openturns/blob/6143a2be4a0e410ea062b8fe5729826aacd6023b/lib/src/Base/Optim/Cobyla.cxx#L260

Setting the constraints of the a, b, c, d might be inappropriate because it uses `ScalarEpsilon` instead of `"TrapezoidalFactory-RhoEnd"`:

https://github.com/openturns/openturns/blob/75893de646ec97ce179742355aded13be8878eb4/lib/src/Uncertainty/Distribution/TrapezoidalFactory.cxx#L96

https://github.com/openturns/openturns/blob/75893de646ec97ce179742355aded13be8878eb4/lib/src/Uncertainty/Distribution/TrapezoidalFactory.cxx#L112

**Comment by josephmure** [comment]
To calrify, this example (now [estimate_multivariate_distribution.py](https://github.com/openturns/openturns/blob/master/python/doc/examples/py_data_analysis/distribution_fitting/plot_estimate_multivariate_distribution.py)) no longer freezes, but only because `SpecFunc::MaxScalar` is divided by 10^6 in [Cobyla.cxx](https://github.com/openturns/openturns/blob/master/lib/src/Base/Optim/Cobyla.cxx#L260).

**Comment by jschueller** [comment]
see #1657

**Comment by mbaudin47** [comment]
My guess is that this might be linked to:
https://github.com/openturns/openturns/blob/6143a2be4a0e410ea062b8fe5729826aacd6023b/lib/src/Base/Optim/algocobyla.c#L1346
