### ISSUE TITLE
The graphs_loglikelihood_contour example has a bug

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1624]
In the page "Plot the log-likelihood contours of a distribution":

https://openturns.github.io/openturns/master/auto_py_graphs/plot_graphs_loglikelihood_contour.html

the plot seems broken:

![image](https://user-images.githubusercontent.com/31351465/96285705-952fe600-0fdf-11eb-8459-c184de6e41d1.png)

The expected output should be:

![image](https://user-images.githubusercontent.com/31351465/96285791-b1cc1e00-0fdf-11eb-928e-d393b1fc0a56.png)

or nicer, with the updated palette. 

@KieranDelamotte : might this be an unexpected consequence of the sphinx-gallery port?

**Comment by regislebrun** [comment]
It is one of the nice consequences of @josephmure 's PR ;-)! Look at the previous log-PDF values, you will see that at least one of the points was out of the estimated distribution range. By convention we exclude the left-end point of the support from the support and keep the right-end point for all the distributions with bounded support. It allows to avoid strange behaviors when several bounded distributions are combined e.g. in a Mixture and one of then has a right-end point equal to the left-end point of the other. So when you estimate the support of your distribution inside of the logLikelihood function by taking the min and max values of the sample you are certain to have one point outside of the support. The PDF is zero, and before the PR a -logMaxScalar value was added to the other logPDF values (in the order of 1.0) so it was still possible to see the evolution of the likelihood function. Now that we add LowestScalar, all the other values are like zero and you draw the iso-values of a constant function equal to LowestScalar! Note that a value of -inf would have give you the exact same graph ;-)!
The fix is to switch to another estimator, like the ones in the different factories of bounded distributions. An admissible estimator is the following:
```
def logLikelihood(X):
    '''
    Evaluate the log-likelihood of a TruncatedNormal on a sample. 
    '''
        samplesize = sample.getSize()
    mu = X[0]
    sigma = X[1]
    a = sample.getMin()[0]
    b = sample.getMax()[0]
    delta = (b - a) / samplesize
    a -= delta
    b += delta
    distribution = ot.TruncatedNormal(mu,sigma,a,b)
    samplelogpdf = distribution.computeLogPDF(sample)
    loglikelihood = -samplelogpdf.computeMean()* samplesize
    return loglikelihood
```
then you get:
![graph1](https://user-images.githubusercontent.com/8220933/96305001-6cb6e480-0ffd-11eb-9939-e943cf60d904.png)

**Comment by josephmure** [comment]
Short version: the old contour plot of the log-likelihood was wrong!

**Comment by josephmure** [comment]
Short version: the old contour plot of the log-likelihood was wrong!

**Comment by regislebrun** [comment]
And the use of exceptions would have made it clearer ;-): nobody would have wonder why iso-lines had disappear if an error message had tell them that the logPDF could not be computed at a given location. I will integrate the fix in my next PR.

**Comment by josephmure** [comment]
Let us simulate what would have happened if we had allowed the log-likelihood function to output minus infinity.

```
import numpy as np
def logLikelihood(X):
    """Dummy function that returns infinity."""
    return [-np.inf]
```

![inf](https://user-images.githubusercontent.com/31989332/96329689-c7792c00-104f-11eb-8236-47dfd3d8301b.png)

The legend of the output "graph" shows that it attempted to plot a minus infinity contour level. This would have told the user that the log-likelihood could take this value, which in turn would have led him to deduce that the likelihood was actually null at some points (or, in this case, all of them) and then to conclude that there was a problem with the domain of the truncated normals.

**Comment by jschueller** [comment]
Regis's point is that it's still silent, which is not ideal when we are maintaining a large library relying heavily on graph automation for its documentation.

**Comment by josephmure** [comment]
That is true, but this could be solved by catching infinities (or NaNs, for that matter) in the graphical classes. We could have an error message like "ValueError: cannot plot infinity". It would be more economical than doing so in the computeLogLikelihood method of every single distribution.

Concerning the deeper issue of infinities vs exceptions: our debate can be reframed as "Should we catch infinities a priori or a posteriori"? 

A priori catching is safer in the sense that users cannot make mistakes (only OpenTURNS developers can!), while a posteriori catching is more flexible, because depending on the application, infinities can be meaningful.

**Comment by jschueller** [comment]
I'm not sure intercepting it at the root is more economical than catching it at the multiple places it can be used.

However I agree it could be useful locally, we're doing so for functions in the Persalys context to discriminate failed points using the setCheckOutput flag, so why not for numerical methods:
https://openturns.github.io/openturns/master/user_manual/_generated/openturns.EvaluationImplementation.html?highlight=evaluationimplementation#openturns.EvaluationImplementation.setCheckOutput

**Comment by regislebrun** [comment]
It's an old problem: to try to suppress the causes or to try to cure the symptoms! BTW in almost all places in the library, when the input argument of a function is outside of the allowed range for the function, an InvalidArgumentException is raised. I really don't see why it should be different here. You learn in undergraduate courses that the log function is defined for x>0, not for x=0. Period. And stop saying that exp(log(x))=x at x=0 to justify that we can compute log(0)=-inf just as if it was a kind of "supernumber". And the argument saying that we can divide MAXSCALAR by 2 to get 1 is correct, but doesn't prove anything. Inf is here only to say that that something is greater than MAXSCALAR, and if x>MAXSCALAR we should have sqrt(x)<x, satisfied by MAXSCALAR but not by inf.

If you bother with performance, a first step is to test things and to see if the impact is large not only when 100% of your sample points are outside of the support, but when a typical small fraction of the points are outside of the support. If the impact is large, we can introduce a private computeLogPDFUnsafe() method allowed to return inf, and use it inside a distribution to implement computePDF() as the exponential of computeLogPDFUnsafe(). Any class outside of the Distribution hierarchy would have to be friend of DistributionImplementation to use it through a myDistribution.getImplementation()->computeLogPDFUnsafe() call in order to **explicitely** allow inf to leak outside of the computePDF/computeLogPDFUnsafe couple.

**Comment by regislebrun** [comment]
And now your shorter version ;-)
