### ISSUE TITLE
Strange difference between SymbolicFunction and PythonFunction wrappers in SORM method

### ISSUE THREAD

**Issue by dmitrygrigoryev** [openturns/openturns#1637]
Hello, 

I tried to use SORM method in `Estimate a probability with FORM` example and found a strange difference between SymbolicFunction and PythonFunction wrappers. If I use the SymbolicFunction all things are OK, but if I wrap deviation formula to the PythonFunction - exception occurred. Exception text is: 
` RuntimeError: NotDefinedException : Error: impossible to compute Tvedt SORM probability, one of the curvatures is < -1/(1+beta). beta=2.21077, curvature=-99562.1`

Maybe I did something wrong? But it looks like a bug.

Here is my experimental Jupyter notebook, to reproduce this strange behavior (checked on OT 1.12 and OT 1.15).
[Python3_OT.zip](https://github.com/openturns/openturns/files/5437077/Python3_OT.zip)

**Comment by jschueller** [comment]
```
import openturns as ot
sfbb = ot.SymbolicFunction(['E', 'F', 'L', 'I'], ['F*L^3/(3*E*I)'])

dist_E = ot.Beta(0.93, 3.2, 2.8e7, 4.8e7)
dist_F = ot.LogNormalMuSigma(30000, 9000, 15000).getDistribution()
dist_L = ot.Uniform(250, 260)
dist_I = ot.Beta(2.5, 4.0, 3.1e2, 4.5e2)
marginals = [dist_E, dist_F, dist_L, dist_I]
# Create the Copula
RS = ot.CorrelationMatrix(4)
RS[2, 3] = -0.2
# Evaluate the correlation matrix of the Normal copula from RS
R = ot.NormalCopula.GetCorrelationFromSpearmanCorrelation(RS)
# Create the Normal copula parametrized by R
copula = ot.NormalCopula(R)

# Create the joint probability distribution
distribution = ot.ComposedDistribution(marginals, copula)
distribution.setDescription(['E', 'F', 'L', 'I'])


# create the event we want to estimate the probability
vect = ot.RandomVector(distribution)
G = ot.CompositeRandomVector(sfbb, vect)
event = ot.ThresholdEvent(G, ot.Greater(), 30.0)
# Define a solver
optimAlgo = ot.Cobyla()
optimAlgo.setMaximumEvaluationNumber(1000)
optimAlgo.setMaximumAbsoluteError(1.0e-10)
optimAlgo.setMaximumRelativeError(1.0e-10)
optimAlgo.setMaximumResidualError(1.0e-10)
optimAlgo.setMaximumConstraintError(1.0e-10)
# Run SORM
algo = ot.SORM(optimAlgo, event, distribution.getMean())
algo.run()
result = algo.getResult()
print(result.getEventProbabilityTvedt())

def cantilever_beam_bb(X):
    E, F, L, I = X
    d = F*L**3/(3*E*I)
    #print('X=', [E, F, L, I], 'd=', d)
    return [d]
pfbb = ot.PythonFunction(4, 1, func=cantilever_beam_bb)
G = ot.CompositeRandomVector(pfbb, vect)
event = ot.ThresholdEvent(G, ot.Greater(), 30.0)
algo = ot.SORM(optimAlgo, event, distribution.getMean())
algo.run()
result = algo.getResult()
print(result.getEventProbabilityTvedt())
```

**Comment by regislebrun** [comment]
@dmitrygrigoryev It is due to the way gradients and hessians are computed: they are obtained using symbolic differentiation in the case of symbolic functions, so they are essentially computed up to machine precision, and they are computed using finite differences in the case of Python functions unless you also provide an implementation for them. You can tune the finite difference parameters to get better results. I attach an updated version of your notebook with the two options. I had to change the ot.Event into ot.ThresholdEvent as it is the new class name for the events based on a threshold and a comparison operator and the old interface has been deprecated. It should work with OT 1.15 too.
[Python3_OT_RLN.zip](https://github.com/openturns/openturns/files/5438945/Python3_OT_RLN.zip)

**Comment by dmitrygrigoryev** [comment]
@regislebrun, @jschueller  Thanks for help and explanation. Idea from Regis notebook works.
