### ISSUE TITLE
SORM RunTimeError

### ISSUE THREAD

**Issue by Aorus42** [openturns/openturns#1693]
Hello,
I am running reliability calculations and want to compare the outputs of FORM, SORM, and crude Monte Carlo (the latter for validation purposes). Results from FORM and MC tend to align well, but SORM often yields very large errors or fails to run entirely with the following error code:

`RuntimeError: NotDefinedException : Error: impossible to compute Breitung SORM probability, one of the curvatures is < -1/beta. beta=1.73169, curvature=-2930.51`

I gather from this that the limit state function I am using doesn't play nice with SORM for some reason - are there parameter values I can change to remedy this?

The FORM/SORM algorithm parameters I have set currently are shown below:

```
optimizer = ot.Cobyla()
eps = 1e-7
n_eval=10000
optimizer.setMaximumEvaluationNumber(n_eval)
optimizer.setMaximumAbsoluteError(eps)
optimizer.setMaximumRelativeError(eps)
optimizer.setMaximumResidualError(eps)
optimizer.setMaximumConstraintError(eps)

algo = ot.SORM(optimizer, my_event, rv_vect.getMean())
result = algo.run
```

Thank you!

**Comment by regislebrun** [comment]
Hi,

Thanks for using OT! The most probable reason why your computation fails is the computation of the Hessian of the objective function at the design point. If you don't provide a specific implementation for the Hessian, OT uses finite differences.

The default behavior is to use centered finite differences with the same step in all the directions, equal to ResourceMap.GetAsScalar( "CenteredFiniteDifferenceGradient-DefaultEpsilon" ) for the gradient (1e-5 by default) and ResourceMap.GetAsScalar( "CenteredFiniteDifferenceHessian-DefaultEpsilon" ) for the Hessian (1e-4 by default). The default values are optimal assuming that the input variables varies around 1 and the numerical noise affecting the output is of order 1e-16, the machine precision.

You can change it in many ways in order to get better results. You can of course implement the Hessian by yourself and provide it using the setHessian() method of your Function, but you can also tune the finite difference parameters. In order to gain speed during the iterations, in the case where you use a gradient-based optimization algorithm (which is not the case with Cobyla) you can use a non-centered finite difference approximation of the gradient, for a cost of d+1 evaluations of the function instead of 2d evaluations. In order to improve the accuracy, you can tune the finite difference step, either by choosing a more adapted value, or different values according to the directions, or a smooth transition between an absolute step and a relative step.

You can check the following classes: `ConstantStep` and `BlendedStep` for the step control, `CenteredFiniteDifferenceGradient`, `NonCenteredFiniteDifferenceGradient`, `CenteredFiniteDifferenceHessian` for the finite difference method, and https://github.com/openturns/openturns/blob/master/python/test/t_CenteredFiniteDifferenceHessian_std.py for an example on how to change the Hessian implementation of a function.

Note that if your function has no Hessian at the design point (e.g. it has a corner) the curvatures are not defined and your computation will still fail.

Cheers

Régis

**Comment by jschueller** [comment]
I think there's no bug we can fix here then. Feel free to reopen if you think something should be done.
