### ISSUE TITLE
Correlation matrix not definite positive

### ISSUE THREAD

**Issue by Tangzl922** [openturns/openturns#1708]
Hi,

I've met a problem while obtaining the normal copula to compute ANCOVA indices. The error says the correlation matrix is not definite positive. I checked the eigenvalues but found they were all positive, although one of them is close to 0. 

Here are the codes and results.
`S = ot.CorrelationMatrix(5)

S[1,0] = 0
S[2,0] = 0.844
S[3,0] = 0.716
S[4,0] = -0.972
S[2,1] = 0.494
S[3,1] = 0.528
S[4,1] = 0.189
S[3,2] = 0.860
S[4,2] = -0.725
S[4,3] = -0.548

R = ot.NormalCopula().GetCorrelationFromSpearmanCorrelation(S)`

![image](https://user-images.githubusercontent.com/73125328/103284645-117d7700-49dc-11eb-9fe8-f9194d3b0588.png)

![image](https://user-images.githubusercontent.com/73125328/103284692-3245cc80-49dc-11eb-91c8-7de3caf730de.png)

**Comment by regislebrun** [comment]
S is definite positive, but not its transform as a correlation for a normal copula. To make things clearer, given a Spearman correlation S, if it can be obtained as the Spearman correlation of a normal copula with correlation R, then we have $R_{ij}=2\sin(S_{ij})$. The matrix S can be definite positive but not the matrix R: it only means that S cannot be obtained from a normal copula.

**Comment by Tangzl922** [comment]
Yes I agree. 
Since the composed distribution is required to compute ANCOVA indices, what can we do in this case when we have problem with getting correlation R given a Spearman correlation?

**Comment by regislebrun** [comment]
The first step is to ask yourself from where this Spearman correlation comes from. If it has been estimated from data, there is a ball in which any correlation matrix is equally relevant than this one, so you can choose another correlation for which the transformation leads to an SPD matrix. Another way to save the situation is to compute R using the above formula, then its eigenvalues, and to shift R in order to recover its SPD property. Yet another way is to use an empirical Bernstein copula with the given Spearman correlation. All these options are not really hard to code, but unfortunately I don't have too much time to play with it right now. If you can wait for next week I will have more time (don't hesitate to ring a bell if you get no news).

**Comment by Tangzl922** [comment]
It's not a very urgent problem, thanks for your help! 
I will also try the methods you mentioned above. If I succed, I will give you a feedback then.
