### ISSUE TITLE
Misleading y labels in VisualTest.DrawPairsMarginals()

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1710]
The following script:
```
import openturns as ot

d = ot.Normal([0.0]*5, [1e-6, 1e-2, 1e0, 1e2, 1e3], ot.IdentityMatrix(5))
s = d.getSample(100)
ot.Show(ot.VisualTest.DrawPairsMarginals(s, d))
```
produces:
![Figure_1](https://user-images.githubusercontent.com/8220933/103550685-90295700-4ea9-11eb-9b99-54ff1e164664.png)
All the marginal distributions look the same despite the fact that they differ by orders of magnitude. Sharing the same y axis for sample points and PDF values is strange, as it looks like a PDF could take negative values.

**Comment by jschueller** [comment]
indeed, here the pdf scale does not follow the cloud scale

currently viewer.py assumes we have the same scale in every cell so we can hide the inner ticks:
```
                    # hide inner ticks
                    if i < graph.getNbRows() - 1:
                        axes[0].set_xticklabels([])
                    if j > 0:
                        axes[0].set_yticklabels([])
```

maybe this information could be moved inside the graph data but I dont know if horizontal ticks on the pdfs will display nicely

**Comment by mbaudin47** [comment]
I agree that the Y axis of the PDFs on the diagonal should have their own Y ticks labels. This is because there is no reason that the Y ticks of the first PDF is equal to the Y ticks of the others. The Y ticks of the projections could, however, have their X / Y ticks hidden when appropriate. The disabling / enabling the X / Y ticks could be specific to the type of graph: `DrawPairsMarginals` could have its own management, so that we show the Y ticks of the graphs on the diagonal. 

Please also consider #1711 on this topic.
