### ISSUE TITLE
The LinearModelStepwiseAlgorithm has no example

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1758]
The API example does not exist:
http://openturns.github.io/openturns/master/user_manual/response_surface/_generated/openturns.LinearModelStepwiseAlgorithm.html
and there is no extended example in the "Examples" section.

A question on this algorithm was asked on the "statsmodels" forum:

https://groups.google.com/g/pystatsmodels/c/es7Jd_ZTTgE/m/hE8toD8rBAAJ

@JPelamatti Would you be interested in creating one or several examples on this topic? I have the intermediate material that we used to create the features, the examples, the scripts, etc...

**Comment by mbaudin47** [comment]
The example can be based on:

https://github.com/openturns/openturns/blob/master/python/test/t_LinearModelStepwiseAlgorithm_std.py

**Comment by jorgeribeiro161** [comment]
Let me explain the problem:
I am a SAS user with 30 years of modelling experience, and 3 months using Python, which I am impressed with.
I need to write a chapter of a book to use Stepwise, Forward and Backward selection method.
I can include openturns in my book if someone helps me.
I have done everything in R and SAS and I can share the code and data sets.
Thanks
Jorge

**Comment by mbaudin47** [comment]
This sounds great. I must discuss this with my colleagues to clarify who and how we can help you, but I am almost sure that we can get this right. I will let you know within a few days. Please ping us if required.

**Comment by jorgeribeiro161** [comment]
Many thanks

**Comment by sofianehaddad** [comment]
Hi all,
Initially we had some examples on the deprecated `otlm` that were not integrated into the library. Have a look at [anova example](https://github.com/openturns/otlm/blob/master/python/doc/examples/anova.rst),  [stepwise basic example](https://github.com/openturns/otlm/blob/master/python/doc/examples/stepwise.rst)

Now we have done some important work on the global documentation side, we need to see how to embed these examples (relying on `csv` files) + more examples (relying on our use cases). I think it is important also because when implementing the functionality, in comparison with `R`, we tracked some issues in `R step` (see [validation](https://github.com/openturns/otlm/blob/master/python/doc/developer_guide/validation/stepwise.rst) for example)

**Comment by mbaudin47** [comment]
We have discussed this and will work on the topic within a few days / weeks.

**Comment by jorgeribeiro161** [comment]
Many thanks
Merci
Jorge
