### ISSUE TITLE
The drawPDF method of Histogram sometimes fail

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1784]
The code:
```
import openturns as ot
sample = ot.Sample(100, 1)
for i in range(100):
    sample[i, 0] = 1.0e5  # 1.e4 plots a point, 1.e3 is correct
ot.HistogramFactory().build(sample).drawPDF()
```
produces:
```
TypeError: InvalidArgumentException : Error: cannot draw a PDF with xMax >= xMin, here xmin=100000 and xmax=100000
```

**Comment by regislebrun** [comment]
* There is no drawPDF() method for the HistogramFactory class, hence the title of the issue is misleading
* Your sample is constant, thus it is a bad idea to use an histogram to model it. If you read the warnings, you see the following message: "All the values are equal in the given sample. We switch to a bandwidth equal to QuantileEpsilon.". It should be an exception (and was an exception at one time), here is the only bug I see. BTW you also have a first message telling you that:
"The first and third quartiles are equal, which means that many values are repeated in the given sample. Switch to the standard deviation-based bandwidth.", which is precisely the problem you get a few lines later when drawing the PDF.
* QuantileEpsilon is something like 1e-14, so you get a uniform distribution U(10^5-10^-14,10^5+10^-14) for which the two bounds are so close that the automatic computation of bounds fails in drawPDF(). If you provide the bounds of the graph it works: ot.HistogramFactory().build(sample).drawPDF(1e5-1e-10,1e5+1e-10) gives you something... not very useful!
So the question is, IMO, should we reject a constant sample in HistogramFactory? Should we build a Dirac in this case?

**Comment by josephmure** [comment]
>       So the question is, IMO, should we reject a constant sample in HistogramFactory? Should we build a Dirac in this case?

I am rather in favor of a Dirac. It is the only sensible distribution that can be built from a constant sample.

**Comment by regislebrun** [comment]
I have evolved in my position since I post my answer. Is it the role of HistogramFactory to build a Dirac distribution because the sample does not correspond to a continuous distribution? A Dirac cannot be returned by buildAsHistogram(), so the build() method would have a different behavior than the buildAsHistogram() method, which is a singularity wrt all the other factories.
IMO it is the role of a more general class to select the most relevant model for a given dataset, relying on all the individual factories.

**Comment by jschueller** [comment]
I agree, we must reject constant samples at least in continuous factories.
