### ISSUE TITLE
TruncatedDistribution fails to compute quantiles

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1870]
The following code:

```
import openturns as ot
unif = ot.Uniform(0.0, 1e12)
trunc = ot.TruncatedDistribution(unif, 0.25, 2.0)
trunc.drawQuantile()
```

produces:

![truncated_dist_wrong](https://user-images.githubusercontent.com/31989332/123780735-c9300a80-d8d3-11eb-9249-69dbd7858976.png)

@MerlinKeller A consequence of this bug is the possibility of getting samples lower than the lower bound of the truncated distribution.

**Comment by jschueller** [comment]
this happens because the probability of the truncation interval is of the same order of quantile epsilon, ok with:
`ot.ResourceMap.SetAsScalar('Distribution-DefaultQuantileEpsilon', 1e-14)`

I think it should always be smaller not in absolute but relative to the weight of the truncation interval / range of the original distribution, ie `quantileEpsilon = probability * DefaultQuantileEpsilon`
