### ISSUE TITLE
MaximumLikelihoodFactory has two consistent, hidden, bugs

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1930]
In MaximumLikelihoodFactory, the gradient() method of the `LogLikelihoodGradient` internal object computes the gradient of the log-likelihood:

https://github.com/openturns/openturns/blob/b5797d7e4a71c71faf86df51f26ad0d8d551ad08/lib/src/Uncertainty/Distribution/MaximumLikelihoodFactory.cxx#L262

The code is wrong, because the value returned is not the gradient but is the gradient divided by the sample size. This is because `computeMean()` is used. To get the exact gradient, we must multiply by the sample size. Here is the derivation:

![image](https://user-images.githubusercontent.com/31351465/145269383-5e213cb6-dbeb-462d-a839-2609ee586670.png)

The bug has, weirdly, no impact, because 
* the method `gradient()` is not public,
* the "pseudo"-gradient is consistently written depending on the pseudo - log-likelihood. 

Indeed, the log-likelihood return by the "()" operator of the `LogLikelihoodEvaluation` internal class has the same bug:

https://github.com/openturns/openturns/blob/b5797d7e4a71c71faf86df51f26ad0d8d551ad08/lib/src/Uncertainty/Distribution/MaximumLikelihoodFactory.cxx#L173

The returned value is not the log-likelihood, but the log-likelihood divided by the sample size. This way, both bugs are consistent, but are _still_ bugs :) .

This is why I suggest to fix them both so that their name match their content.

**Comment by regislebrun** [comment]
It all depends on what you want to refer to talking about maximum likelihood. The name of the factory is correct, as well as its result as maximizing L, log(L) or log(L)/n is the same. We used the mean value *on purpose* and the fact that we called it log-likelihood instead of mean log-likelihood is 100% laziness. Using the mean log likelihood allows to compare values when using different sample sizes as it converges toward the entropy of the distribution (i.e. a fixed quantity) instead of diverging toward +/-inf.

**Comment by jschueller** [comment]
MaximumLogLikelihoodDividedByMeanFactory ^^

**Comment by mbaudin47** [comment]
Ok, that is fine to me then. If the method was public, that would be a true bug, in the sense that it would prevent from being able to reference values or to other software (this is the case for the BIC, but this is off-topic). This is why I close this issue: we may as well reopen it if this becomes an actual issue.
