### ISSUE TITLE
Some script fails

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2213]
The following script fails, but I do not know why.

```python
import openturns as ot


def centeredSumOfProduct(sampleA, sampleB, center):
    sampleA -= center
    sampleB -= center
    return sampleA.asPoint().dot(sampleB.asPoint())

YA = ot.Sample(10, 1)
center = 0.0
sumOfSquaresOfG = centeredSumOfProduct(YA, YA, center)
```
I guess that the operator "-=" does something wrong.

**Comment by regislebrun** [comment]
The "-=' is not the root cause of the bug, but rather a double free of the memory pointed by YA. If you change your script the following way it runs smoothly (but the bug is still there):
```
import openturns as ot


def centeredSumOfProduct(sampleA, sampleB, center):
    sampleA -= center
    sampleB -= center
    return sampleA.asPoint().dot(sampleB.asPoint())

YA = ot.Sample(10, 1)
center = 0.0
sumOfSquaresOfG = centeredSumOfProduct(YA, ot.Sample(YA), center)
```
For a reason unknown to me, the layer generated by SWIG tries to free sampleA and sampleB, but they are both pointers toward YA...
