### ISSUE TITLE
DiracCovarianceModel.discretize() is buggy

### ISSUE THREAD

**Issue by JPelamatti** [openturns/openturns#2296]
It looks like the discretize method of the DiracCovarianceModel does not work properly, and always returns an identity matrix. A short example is provided below : 
```

import openturns as ot

ot.RandomGenerator.SetSeed(1)

vec = ot.UserDefined([[1],[2],[3]],[1,1,1]).getSample(10)
cov = ot.DiracCovarianceModel()

print(vec)
print(cov.computeAsScalar(vec[0],vec[1]))
print(cov.computeAsScalar(vec[0],vec[3]))
print(cov.discretize(vec))
```

**Comment by jschueller** [comment]
maybe because you're using the default ctor ?

**Comment by JPelamatti** [comment]
Hmmm looks like I obtain the same issue if I use the normal ctors:

`import openturns as ot

ot.RandomGenerator.SetSeed(1)

vec = ot.UserDefined([[1],[2],[3]],[1,1,1]).getSample(10)
vec.stack(vec)

covModel2 = ot.DiracCovarianceModel(2)

print(covModel2.discretize(vec))`

**Comment by jschueller** [comment]
what if you pass your own non-diagonal cov matrix to the ctor ?

**Comment by sofianehaddad** [comment]
@JPelamatti I don't understand. What are you expecting as output?

**Comment by sofianehaddad** [comment]
Oh I see....

**Comment by jschueller** [comment]
I still dont understand

**Comment by sofianehaddad** [comment]
The `discretize` effectively returns a diagonal covariance matrix because we did not put in mind a discretization over a `Sample` containing duplicate values. We designed the class as a `white noise`, meaning we only consider acting on the diagonal...

So the question is :
 - Should we keep the behaviour as is and rename the class into `WhiteNoiseDistribution` for example ? Here the class acts as a `white noise` !
 - Or should we consider a `Dirac` model returning effectively $\delta(||X_i-X_j||)$
 - or other solutions ?

In the second case we might generate non inversible matrices....

**Comment by JPelamatti** [comment]
Exactly @sofianehaddad , the duplicates are not taken into consideration in the discretize method, making the result incoherent with the 'computeAsScalar' method.
I believe the non inversible matrices are a fairly extreme case, in fact I can only see it happening when discretizing a constant sample, but I might be missing something. In theory, the dirac kernel is supposed to be at least semi-definite positive

**Comment by jschueller** [comment]
DiracCovarianceMOdel should test for duplicates in the nodes, with an option in the RM
