### ISSUE TITLE
Instantiate a Distribution from a dictionary of parameters

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2394]
In a Python project, I'm creating a function to instantiate any probability distribution available in interfaced UQ libraries (SciPy, OpenTURNS, ...).

The signature is `create_distribution(class_name, **kwargs)` (the choice of keyword arguments is on purpose) and the expected usage is `normal = create_distribution("Normal", mu=1, sigma=2)` or `normal = create_distribution("Normal",  sigma=2, mu=1)`. As in OpenTURNS the constructors do not accept keyword arguments, this function instantiates the normal distribution as `getattr(ot, class_name)(*sorted_kwargs.values())` where `sorted_kwargs` is the dictionary `kwargs` sorted according to the constructors available in `ot.Normal.__doc__`. Unfortunately some distributions do not provide a documentation of the constructors (e.g. `Exponential`).

Would it be possible to document all the constructors? 

When a parameter has a default value in a constructor, would it be possible to replace this constructor by two constructors: one with this parameter and one without it?

Is there an alternative to instantiate an OpenTURNS class from a dictionary of parameters?

**Comment by jschueller** [comment]
in OT we preferably dont want to list the C++ constructors available in the Python doc to not confuse users as "constructor" does not exist in Python (there is only one __init__ method), for example Exponential:
https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Exponential.html
instead the "optional" parameters here must be understood as optional positional arguments instead of keyword arguments
but other times its not possible to do that and we have to list the constructors because their signature changes completely, eg for the Gaussian which accepts a single d int, or mu/sigma etc:
https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Normal.html
so to keep thing simple we should try to have fewer ctors as possible in the C++ side

also you should build a distribution from the full list of parameters by creating a default instance and then calling setParameters, something like:
```
instance = getattr(ot, class_name)()
instance.setParameters([1,2,3])
```
or using the factory classes:
```
factory = getattr(ot, class_name+"Factory")()
instance = factory.build([1,2,3])
```

**Comment by jschueller** [comment]
no, it wont work, you will still need to pass the values in the correct order

**Comment by mdelozzo** [comment]
Unfortunately `getParameterDescription`  does not return `[d, mu, sigma, R, Sigma]` but `["mean_0","standard_deviation_0"]` (or something different if we do not use the default values of the parameters). 

```python
from openturns import Normal

assert Normal().getParameterDescription() == ["mean_0","standard_deviation_0"]
assert Normal(2).getParameterDescription() == ["mean_0", "standard_deviation_0", "mean_1", "standard_deviation_1", "R_1_0"]
```

**Comment by jschueller** [comment]
yes, I think this one is an exception though

**Comment by mdelozzo** [comment]
An exception or a bug? 

It would be a great new for me if for any distribution, 

- `getParameterDescription` returns the names of all the possible parameters with the same order as the C++ constructors,
- the docstring of the class documents these parameters with the same names as the ones returned by `getParameterDescription`.

**Comment by jschueller** [comment]
it should be the case already, except for multivariate distributions like Normal etc where we need to name parameters with a number

**Comment by mdelozzo** [comment]
But the names suffixed by numbers (e.g. `mean` / `mean_0`) do not correspond to the names documented in the docstrings (e.g. `mu`).

So creating a generic Python function `create_distribution(class_name, **parameters)` where `class_name` can be the name of any OT class implementing a distribution seems to be impossible. I think that the only solution is to create it as `create_distribution(class_names, *args, **kwargs)`.

**Comment by jschueller** [comment]
hi @mdelozzo, we renamed multivariate parameters:
```
Out[3]: Normal().getParameterDescription()
Out[3]: [mu_0,sigma_0]
```
let me know if you need anything more, or if this can be closed
