### ISSUE TITLE
Rename ComposedDistribution to JointDistribution ?

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#2427]
I think its the correct math term, what do you think ?

**Comment by jschueller** [comment]
any thoughts @regislebrun ?

**Comment by jschueller** [comment]
TODO: deprecated in 1.23, removed in cxx in 1.25, removed in Python in 1.26

**Comment by regislebrun** [comment]
The initial name was chosen to underline the composition of the copula with the univariate marginal distributions in order to get the joint distribution, but I agree on the fact that it sounds strange.
In the same spirit, we could rename ComposedCopula into BlockIndependentCopula, in order to mimic the BlockIndependentDistribution (and here, the name look good to me).

**Comment by jschueller** [comment]
done
