### ISSUE TITLE
C++ Test SmolyakExperiment_std fails on arm64, ppc64el, s390x

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2443]
### What happened?

Dear Maintainer,

While packaging version 1.21.1 in Debian, I saw that the C++ test SmolyakExperiment_std is consistently failing on arm64, ppc64el, s390x.

Enclosed is the build log on arm64, see lines 10696 to 13684.
[arm64_log.zip](https://github.com/openturns/openturns/files/13179687/arm64_log.zip)

### How to reproduce the issue?

```shell
Run the C++ unit tests on one of the platforms listed above.
```

### Version

1.21.1

I did not package version 1.21, so I am not able to tell if the issue was showing up in 1.21.

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
probably comes from the merge part:
```
// Test 2 : Disable merge
  ResourceMap::SetAsBool("SmolyakExperiment-MergeQuadrature", false);
  Point weightsBis(0);
  Sample nodesBis(experiment.generateWithWeights(weightsBis));
  printNodesAndWeights(nodesBis, weightsBis);
  const int experimentSizeBis = experiment.getSize();
  fullprint << "experimentSizeBis = " << experimentSizeBis << std::endl;
  assert_equal(experimentSizeBis, 83);
  //
  const int sizeBis(nodesBis.getSize());
  const int dimensionBis(nodesBis.getDimension());
  const int weightDimensionBis(weightsBis.getDimension());
  assert_equal(sizeBis, 83);
  assert_equal(dimensionBis, 3);
  assert_equal(weightDimensionBis, 83);
  ResourceMap::SetAsBool("SmolyakExperiment-MergeQuadrature", true);

```

**Comment by jschueller** [comment]
it comes from the merge part with a zero tolerance, so it comes down to testing a==b with doubles, bad idea

**Comment by pgrt** [comment]
Hi @jschueller,

Thanks! Indeed, removing this piece of code fixed the build on the problematic architectures.

Have a great week!

**Comment by mbaudin47** [comment]
I do not agree with the way the bug was "fixed", because removing the unit test does not improve the code: if the test test, this must be because something is wrong.

Here is the purpose of the unit test.
The goal of this part is to show that there are two different ways to prevent the algorithm from merging duplicate nodes:
- either set the "SmolyakExperiment-MergeQuadrature" boolean key to to false (line 404),
- or set the "SmolyakExperiment-MergeRelativeEpsilon" and "SmolyakExperiment-MergeAbsoluteEpsilon" real keys to zero with a "SmolyakExperiment-MergeQuadrature" set to true.

This part of the test shows that the results are the same. Hence, it proves that the management of these ResourceMap keys is correctly performed. Here is the expected behavior:
- with merging enabled: 69 nodes (see line 403)
- with merging disabled and default tolerances : 83 nodes (see lines 405 and 416)
- with merging disabled and customized tolerances : 83 nodes (see lines 421 and 430).

If we remove this part of the test, we cannot guarantee that good behaviour anymore. In other words, removing or changing these keys and introducing bugs may go unnoticed in future releases.

This is why I suggest to reopen the issue and look further. Is it possible to print the number of computed nodes and see its value? This would allow to see why it is different from the reference value 83.
