### ISSUE TITLE
DrawParallelCoordinates is not correct

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#2486]
### What happened?

The method DrawParallelCoordinates selects some realizations which are not included in the Y range selected.

### How to reproduce the issue?

```shell
from openturns import *
from openturns.viewer import View

dataIn = Sample.ImportFromCSVFile('dataIn.csv')
dataOut = Sample.ImportFromCSVFile('dataOut.csv')
eps = 1.e-10
quantileScale = False
minY = -eps
maxY = eps

# No point in ]0.0, eps[
for i in range(dataOut.getSize()):
    if dataOut[i,0] >0.0 and dataOut[i,0] < eps:
        print('i, dataOut = ', i, dataOut[i,0])

# Min of the positive values >0
minVal = dataOut.getMax()[0]
for i in range(dataOut.getSize()):
    if dataOut[i,0] >0.0:
        minVal = min(minVal, dataOut[i,0])

# The minimum positive value is >eps
print('minVal = ', minVal)

# The graph selects wring realizations: some have an y-value > eps!
graphCobweb = VisualTest.DrawParallelCoordinates(dataIn, dataOut, minY, maxY, "red", quantileScale)
graphCobweb.setLegendPosition("bottomleft")
View(graphCobweb).show()
```

### Version

1.22dev

### Operating System

Linux

### Installation media

conda

### Additional Context

[dataIn.csv](https://github.com/openturns/openturns/files/13428419/dataIn.csv)
[dataOut.csv](https://github.com/openturns/openturns/files/13428420/dataOut.csv)

**Comment by regislebrun** [comment]
The problem is here:
https://github.com/openturns/openturns/blob/ac854832326fe8e8894c24c6f564051eb12565ac/lib/src/Uncertainty/StatTests/VisualTest.cxx#L421
and here:
https://github.com/openturns/openturns/blob/ac854832326fe8e8894c24c6f564051eb12565ac/lib/src/Uncertainty/StatTests/VisualTest.cxx#L444

We rely on the ranks to select the filaments, and when the values are converted into ranks some rounding leads to invalid selection in the case of too many repeated values in the output.

A fix is to base the selection using the values provided by the user. A possible fix is to replace the lines 421 to 445 by:
```
  if (quantileScale)
  {
    if ((minValue < 0.0) || (maxValue > 1.0) || (minValue > maxValue))  throw InvalidArgumentException(HERE) << "Error: we must have 0 <= minValue <= maxValue <= 1 when using quantile scale.";
    minRank = size * minValue;
    maxRank = size * maxValue;
  }
  const UnsignedInteger inputDimension = inputSample.getDimension();
  const Sample rankedInput(inputSample.rank());
  const Sample rankedOutput(outputSample.rank());
  // Create the graph
  Graph cobWeb(String(OSS() << "Parallel coordinates - " << outputSample.getDescription() << " vs " << inputSample.getDescription()), "", "", false, "topright");
  // First discriminate the filaments: draw the background filaments and memorize the selected ones
  Indices selectedFilaments(0);
  for (UnsignedInteger i = 0; i < size; ++i)
  {
    const Scalar currentRank = rankedOutput(i, 0);
    if ((quantileScale && (currentRank >= minRank) && (currentRank <= maxRank)) ||
        (!quantileScale && (outputSample(i, 0) >= minValue) && (outputSample(i, 0) <= maxValue)))
      selectedFilaments.add(i);
```
BTW there is no gain in converting ranks into integers, the proposed correction assumes that ranks are Scalar and not UnsignedInteger.

**Comment by jschueller** [comment]
before/after:
![cobweb1](https://github.com/openturns/openturns/assets/3832365/4288eff4-b61b-450a-b9ec-2cd1a5cb15cd)
![cobweb2](https://github.com/openturns/openturns/assets/3832365/b1fab50d-5266-43f7-85c2-1ecb0c504cbc)
