### ISSUE TITLE
Binomial quantile computation fails on extreme example

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#2513]
### What happened?

The following fails on my machine:

```python
bin = ot.Binomial(1030, 0.5)
cdf = bin.computeCDF(400) # cdf = 3.8973524662436084e-13
print(bin.computeQuantile(cdf))
```
Output : [0] instead of the expeted [400]

Note that R succeeds:

```R
> qbinom(3.8973524662436084e-13, 1030, 0.5)
[1] 400
```

### How to reproduce the issue?

```shell
See above
```

### Version

master (1.23dev) (same result on pip-installed 1.22rc1)

### Operating System

Linux

### Installation media

from source

### Additional Context

See https://github.com/openturns/openturns/commit/4f3d29c83f6f37b6c6e07ddfecceac225066ffc4

**Comment by josephmure** [comment]
Here is the relevant line:

https://github.com/openturns/openturns/blob/4f3d29c83f6f37b6c6e07ddfecceac225066ffc4/lib/src/Uncertainty/Model/DistributionImplementation.cxx#L2440

And quantileEpsilon is by default set to 1e-12 in the ResourceMap: 

Distribution-DefaultQuantileEpsilon | 1e-12 | float

**Comment by josephmure** [comment]
Another weird thing: the same quantileEpsilon_ attribute is also used further down the code, as tolerance for the x values instead of the cdfs: 

https://github.com/openturns/openturns/blob/4f3d29c83f6f37b6c6e07ddfecceac225066ffc4/lib/src/Uncertainty/Model/DistributionImplementation.cxx#L2484

**Comment by regislebrun** [comment]
There are two bugs in DistributionImplementation::computeQuantile:
  * the test against quantileEpsilon_ should be moved after the test for dimension==1. In the current code, Binomial::computeScalarQuantile is not called.
  * cdfEpsilon_ should be used instead of quantileEpsilon_, as cdfEpsilon_ is a tolerance for a probability (i.e something in the range [0,1]) and quantileEpsilon_ is a tolerance for an arbitrary real number.

Regarding the call to Brent, when you solve an equation $F(x)=q$, with $0<q<1$, you have 3 different tolerances:
  * the absolute tolerance on x, on an unknown scale
  * the relative tolerance on x, on a unit scale
  * the residual tolerance, on a unit scale because F is a CDF

It is why cdfEpsilon_ is used twice and quantileEpsilon_ only once in the call to Brent. Maybe not the best idea but at least there is a reason for this choice ;-)

**Comment by jschueller** [comment]
looks I already tried that, but I dont recall why I dropped it:
https://github.com/openturns/openturns/pull/2092
