### ISSUE TITLE
ComputeQuantile for discrete variables

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#2552]
### What happened?

We have a discrete variable, and we want to calculate its quantile of order p.
The two following methods should be identical: 
computeQuantile(p) and computeQuantile(1-p, True).
But the results obtained differ....

### How to reproduce the issue?

```shell
from openturns import *

n=16
alpha = 0.75
bin = Binomial(n, alpha)

proba = 0.95
q1 = bin.computeQuantile(proba)[0]
q2 = bin.computeQuantile(1-proba, True)[0]
print('q1, q2 = ', q1, q2)

# Test q1: 
print(bin.computeCDF(q1))
# 0.9899774042423815 > proba ==> ok!
# Test q2: 
print(bin.computeCDF(q2))
# 0.9365235602017492< proba ==> problem!
```

### Version

1.23dev

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
so it's a doc-only problem ?

**Comment by mbaudin47** [comment]
As surprising as it seems, I encountered exactly the same bug at the same time :). This is because we are working on the confidence intervals of a quantile, known as "Wilks's method". In this method, we want to compute indices $k_1$ and $k_2$ such that $\mathbb{P}(K \leq k_1)\leq \beta_1$ and $\mathbb{P}(K \geq k_2) \geq \beta_2$ where $K$ is a binomial distribution. This amounts to compute quantiles of the binomial distribution. But this only motivates the topic and is not relevant to solve the bug.

It is not a doc problem, but an issue in the implementation of `computeQuantile(False)`. Consider the following code, which compute the inverse of the complementary CDF function at point $\alpha = 0.9$:
```python
n = 3
p = 0.5
n_points = 1000
distribution = ot.Binomial(n, p)
x = distribution.computeQuantile(0.9, True)
```
prints:
```
x =  [-1]
```
This is a bug, since the quantile of a Binomial distribution is in the set $\set{0, ..., n}$. Hence, $x=-1$ cannot be a quantile.

To make this clearer, I compared OpenTURNS' [Binomial.html](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Binomial.html) with SciPy's [binom.html](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binom.html).

```python
# %%
import openturns as ot
import openturns.viewer as otv
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import MaxNLocator
from scipy.stats import binom

# %%
n = 3
p = 0.5
n_points = 1000
distribution = ot.Binomial(n, p)
fig = plt.figure(figsize=(6.0, 5.0))
fig.add_subplot(2, 2, 1)
alpha_array = np.linspace(-0.1, 1.1, n_points)
x_array = [distribution.computeQuantile(alpha) for alpha in alpha_array]
plt.plot(alpha_array, x_array)
plt.xlabel(r"$\alpha$")
plt.ylabel(r"$F^{-1}(\alpha)$")
plt.title(f"OpenTURNS, computeQuantile(False)")
plt.grid()
plt.xlim(-0.1, 1.1)
#
fig.add_subplot(2, 2, 2)
x_array = [binom.ppf(alpha, n, p) for alpha in alpha_array]
plt.plot(alpha_array, x_array)
plt.xlabel(r"$\alpha$")
plt.ylabel(r"$F^{-1}(\alpha)$")
plt.title(f"SciPy, ppf")
plt.xlim(-0.1, 1.1)
plt.grid()
_ = plt.suptitle(f"Quantile function of B({n}, {p})")
#
fig.add_subplot(2, 2, 3)
alpha_array = np.linspace(-0.1, 1.1, n_points)
x_array = [distribution.computeQuantile(alpha, True) for alpha in alpha_array]
plt.plot(alpha_array, x_array)
plt.xlabel(r"$\alpha$")
plt.ylabel(r"$\overline{F}^{-1}(\alpha)$")
plt.title(f"OpenTURNS, computeQuantile(True)")
plt.xlim(-0.1, 1.1)
plt.ylim(-1.2, 3.2)
plt.grid()
#
x_array = [binom.isf(alpha, n, p) for alpha in alpha_array]
fig.add_subplot(2, 2, 4)
plt.plot(alpha_array, x_array)
plt.xlabel(r"$\alpha$")
plt.ylabel(r"$\overline{F}^{-1}(\alpha)$")
plt.title(f"SciPy, isf")
plt.xlim(-0.1, 1.1)
plt.ylim(-1.2, 3.2)
ax = fig.gca()
ax.yaxis.set_major_locator(MaxNLocator(integer=True))
plt.grid()
plt.subplots_adjust(wspace = 0.5, hspace = 0.5, top = 0.85)
_ = plt.suptitle(f"Inverse survival function of B({n}, {p})")
```

This produces:

![image](https://github.com/openturns/openturns/assets/31351465/a29fbea2-67df-4713-8be6-48fdcdc923b2)

The two top figures show that the `quantile(False)` (which is the default) function is the same for OpenTURNS and SciPy. But the `quantile(True)` are very different. I do not claim that OpenTURNS is wrong here, but there is an obvious difference that should be explained. Furthermore, there is a bug in that OpenTURNS sometimes creates a negative quantile, which is a bug.

**Comment by mbaudin47** [comment]
It seems that there is a contagious quantile bug spreading in the Issues: #2548, #2541 and this one.

Here is an attempt to clarify what may be implemented. The definition of a quantile is:

$$
F^{-1}(\alpha) = \textrm{inf} \set{x \in \mathbb{R}  |  \alpha \leq F(x)}
$$

for any $\alpha \in [0,1]$. This defines the inverse of the CDF. 

Let us introduce the complementary CDF as:

$$
\overline{F}(x) = 1 - F(x)
$$

for any $x$. For any random variable, this means:

$$
F(x) = \mathbb{P}(X \leq x), \qquad \overline{F}(x) = 1 - \mathbb{P}(X \leq x) = \mathbb{P}(X > x)
$$

for any $x$.
For a discrete random variable, changing $\leq$ into $>$ can make a difference. Similarly, the inverse of the complementary CDF may be defined as:

$$
\overline{F}^{-1}(\alpha) = \textrm{inf} \set{x \in \mathbb{R}  |  \alpha \leq \overline{F}(x)}
$$

for any $\alpha \in [0,1]$.

For the binomial distribution, if $\alpha$ is close to 1, then there can be no quantile which exceeds the given probability.

For example, consider the binomial distribution with parameters $n = 3$ and $p = 0.5$. We have $F(0) = 0.125$ and $\overline{F}(0) = 0.875$. Hence, for any $\alpha \in (0.875, 1]$, there is no quantile which can exceed a CDF value greater than $\alpha$.

![image](https://github.com/openturns/openturns/assets/31351465/9ea4f0da-4d1d-478d-81b9-214fd9acd837)

**Comment by adutfoy** [comment]
I add another bug but I think they are all linked. It concerns the method computeBilateralConfidenceInterval.
We condider x following a Binomial(n, alpha) and we want to calculate the interval [a,b] such that:
 $P(X \in [a,b]) = \beta$.
The method computeBilateralConfidenceInterval finds q such that b is the quantile of order (1+q)/2 of X and a the quantile of order (1-q)/2 of X:
$a = F_{\alpha, n}^{-1}((1-q)/2)$ and $b = F^{-1}_{\alpha, n}((1+q)/2)$

```
n=16
alpha = 0.75
bin = Binomial(n, alpha)
beta = 0.90
interval, q =  binomial.computeBilateralConfidenceIntervalWithMarginalProbability(beta)
print('interval bilateral = ', interval)
print('proba marginale = ', q)

borneInf = binomial.computeQuantile((1-q)/2)
borneSup = binomial.computeQuantile((1+q)/2)
print('borneInf, borneSup = ', borneInf, borneSup)
```
We get:
interval bilateral =  [9, 14]
proba marginale =  0.9
borneInf, borneSup =  [9] [15]

The computeQuantile((1+q)/2) and computeQuantile((1-q)/2) are good. The computeBilateralConfidenceIntervalWithMarginalProbability does not give the good interval

**Comment by mbaudin47** [comment]
In the hope to clarify the topic, I created pictures to represent the CDF of a binomial and the complementary CDF. This makes easier to see where the points of discontinuity are involved.

![image](https://github.com/openturns/openturns/assets/31351465/abd71e61-fc1f-457c-8a6c-ba0360c94716)

![image](https://github.com/openturns/openturns/assets/31351465/47eb8e3a-f798-43f1-ad0a-861348355021)

**Comment by adutfoy** [comment]
Michaël,

The definition you propose for $\bar{F}^{-1}$ has a problem: you will always get the lower bound of the range of the distriution $x_{inf}$ (wich may be infinte) because the function $\bar{F}$ is decreasing and you have $\bar{F}(x_{inf})=1 \geq \alpha$!

I think that we should define the  $\bar{F}^{-1}$ as follows: 
$\bar{F}^{-1}(\alpha) = \inf \\{ x | \bar{F}(x) \leq \alpha \\}$.

Thus, if $\alpha$ is on a plate, then $\bar{F}^{-1}(\alpha)$ corresponds to the left bound of the plate. If $\alpha$ is between two plates, then  $\bar{F}^{-1}(\alpha)$ corresponds to the left bound of the lower plate. For example, in the example you drew, we will obtain $\bar{F}^{-1}(0.70) = 4$ and $\bar{F}^{-1}(0.60) = 4$.

This definition can be used for discrete variables (which generate discontinuities in $\bar{F}$) and for variables with a non strictly increasing cdf (which generate plates in $\bar{F}$) .

Furthermore, we can see that $\bar{F}^{-1}(\alpha) = \inf \\{ x | 1-F(x) \leq \alpha \\}= \inf \\{ x | F(x) \geq 1-\alpha \\} = F^{-1}(1-\alpha)$.

I do not know what is implemented in OpenTURNS but I think we should use that definition. In particular, in the method computeQuantile(alpha, True).

In your example, you drew that  $\bar{F}^{-1}(0.70) = 3$ ... but your definition leads to $\bar{F}^{-1}(0.70) = 0$ !

**Comment by mbaudin47** [comment]
> The computeQuantile((1+q)/2) and computeQuantile((1-q)/2) are good. The computeBilateralConfidenceIntervalWithMarginalProbability does not give the good interval

This topic is related to the `computeBilateralConfidenceIntervalWithMarginalProbability()` method, and is not directly related to the `computeQuantile()` method in my opinion: below, I try to explain why. All in all, I think that the bug in `computeBilateralConfidenceIntervalWithMarginalProbability()` should be discussed within a separate issue, so that the two topics are not mixed up. @adutfoy : do you agree on this strategy?

In [^Krishnamoorthy2011] page 3, two methods for constructing a tolerance interval are presented.
- Method A. The eq. 1 page 3 presents a two tail tolerance interval containing a proportion $p$ of the population with confidence $1 - \alpha$.
- Method B. The eq. 2 page 3 presents a tolerance interval controlling percentages in both tails. This leads to quantile levels $(1-p)/2$ and $(1+p)/2$.

As mentioned in [^Krishnamoorthy2011] page 3: "_Because of the discrete nature of the problem, the coverage probability requirement is at least 1 − α, rather than exactly equal to 1 − α._"

Now, back to a confidence interval for a quantile, we can use [^Hahn2011] section 5.2 page 82 which presents a method for this purpose. More precisely, it presents a two-sided confidence interval for a percentile. We can check our results by comparing to the tables A.15a page 318 up to A.15g page 324. If you do this, you will find that [^Hahn2011] uses implicitly method A. I think that method B is as correct as method A to produce an interval with a given coverage: actually, you used method B in your example. Here is the point: I believe that we could:
1. clarify what exactly `computeBilateralConfidenceIntervalWithMarginalProbability()` does ;
2. fix the bug ;
3. provide both A _and_ B methods instead of just one.

[^Krishnamoorthy2011]: Krishnamoorthy, K., Xia, Y., & Xie, F. (2011). A simple approximate procedure for constructing binomial and Poisson tolerance intervals. Communications in Statistics-Theory and Methods, 40(12), 2243-2258.

[^Hahn2011]: Hahn, G. J., & Meeker, W. Q. (2017). _Statistical intervals: a guide for practitioners_. 2nd Edition. John Wiley & Sons. [Lien](https://www.amazon.com/Statistical-Intervals-Practitioners-Researchers-Probability/dp/0471687170)

**Comment by adutfoy** [comment]
ok to dicuss the problem in the method computeBilateralConfidenceInterval in another issue.
Anne

**Comment by jschueller** [comment]
weird, scipy binomial quantile is also < 0
```
from scipy.stats import binom
print(binom.ppf(0.0, 16, 0.75))
```

**Comment by mbaudin47** [comment]
> weird, scipy binomial quantile is also < 0
> 
> ```python
> from scipy.stats import binom
> print(binom.ppf(0.0, 16, 0.75))
> -1
> ```

This makes sense. Indeed, consider the binomial distribution $\mathcal{B}(16,0.75)$ with parameters $n = 16$ and $p = 0.75$. The value of the CDF at point $k = 0$ is:

$$
F(0) = (1 - p)^n = F(0) = 2.328 \times 10^{-10}.
$$

By definition of the quantile of level $\alpha = 0$, we have :

$$
x_0 = \min \set{x \in \mathbb{R} | 0 \leq F(x)}
$$

Since $F(0) > 0$, we must have $x_0 < 0$. The definition of a quantile leads to $-\infty$. But the binomial distribution is discrete. Hence returning -1 plays the role of $-\infty$ here.

**Comment by jschueller** [comment]
interesting link:
https://beta.boost.org/doc/libs/1_62_0/libs/math/doc/html/math_toolkit/pol_tutorial/understand_dis_quant.html

**Comment by mbaudin47** [comment]
Soit $F_{n, \alpha}$ la loi binomiale de paramètres $n$ et $\alpha$.

![image](https://github.com/openturns/openturns/assets/31351465/70ec45ac-fe5a-4921-88bd-6b56ad844a90)

![image](https://github.com/openturns/openturns/assets/31351465/60b1c3be-ca65-4207-a2be-8742558ad417)

**Figure 1.** Fonction de répartition de la loi binomiale de paramètres n et α.

![image](https://github.com/openturns/openturns/assets/31351465/7cfb9e2c-1ff5-47ba-92ea-ff974714619d)

**Figure 2.** Fonction de répartition complémentaire de la loi binomiale de paramètres n et α.

**Comment by jschueller** [comment]
so Q(x)=Sup{x | F(x)=0}

**Comment by adutfoy** [comment]
When p=0, dist.computeQuantile(p) returns sup { x / F(x) = 0 }
It is coherent with the general definition:
dist.computeQuantile(p)  = inf {x in support | F(x) >= p }

**Comment by mbaudin47** [comment]
In OpenTURNS 1.23
```python
import openturns as ot
ot.Binomial(
    59, 0.05
).computeQuantile(0.05)[0]
```
returns 
```
0.0
```
instead of 1.0.
Here the test I used:
```python
alpha = 0.05
beta = 0.05
for n in range(59, 100):
    d = ot.Binomial(n, alpha)
    k = int(
            d.computeQuantile(
                beta
            )[0]
        )
    p1 = d.computeCDF(k-1)
    p2 = d.computeCDF(k)
    check = p1 < beta <= p2
    print(f"n={n}, "
          f"k={k}, "
          f"p(k-1)={p1:.4f}, "
          f"p(k)={p2:.4f}, "
          f"?={check}")
```
This prints:

**Comment by paolamalsot** [comment]
I seem to stumble on a related issue:

Using the lastest development version (1.25dev), I get $F^-1(F(k)) != k$ for F(k) the CDF of the Poisson distribution. The error is usually 1, and does not happen consistently at all k. Moreover, it does not happen when using scipy. See below, where I plot $diff = F^-1(F(k)) - k$

![Image](https://github.com/user-attachments/assets/8769b70e-358e-4c77-80fd-906b8afe2a9a)


Here is the code to reproduce the figure:
````
mu = 2.0
ks = np.arange(10).astype(int).tolist()
results = []

def scipy_via_cdf(k, mu):
    cdf = poisson.cdf(k,mu = mu)
    res_cdf = stats.poisson(mu).ppf(cdf)
    return res_cdf

def scipy_via_sf(k, mu):
    sf = poisson.sf(k,mu = mu)
    res_sf = stats.poisson(mu).isf(sf)
    return res_sf

def openturns_via_sf(k, mu):
    sf = ot.Poisson(mu).computeSurvivalFunction(k)
    res_sf = ot.Poisson(mu).computeQuantile(sf, True)
    return res_sf[0]

def openturns_via_cdf(k, mu):
    cdf = ot.Poisson(mu).computeCDF(k)
    res_cdf = ot.Poisson(mu).computeQuantile(cdf)
    return res_cdf[0]

funs = [scipy_via_cdf, scipy_via_sf, openturns_via_sf, openturns_via_cdf]

results = []
for k in ks:
    for fun in funs:
        res = fun(k, mu)
        results.append(pd.Series({'k': k, 'res': res, 'fun': fun.__name__}))

results_df = pd.DataFrame.from_records(results)

import seaborn as sns
fig, axes = plt.subplots(2, 2, figsize = (5, 5))
results_df["diff"] = results_df["res"] - results_df["k"]
for name, ax in zip(results_df.fun.unique(), axes.flatten()):
    query = results_df.query("fun == @name")
    sns.scatterplot(data = query, x = 'k', y = 'diff', ax = ax)
    ax.set_title(name)
plt.tight_layout()
plt.show()
````

**Comment by jschueller** [comment]
hi @paolamalsot, thanks for the report. Would you mind opening a new dedicated issue ? I would help keeping track of it.
