### ISSUE TITLE
There are implicit forbidden variable names for SymbolicFunction

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2798]
### What happened?

The next code produces the error:
```
TypeError: InvalidArgumentException : Invalid input variable: 'gamma' at index: 0
```
But we cannot find the issue by looking at the code, because it is formally correct. The fixed code is:
```python
full_function = ot.SymbolicFunction(["gamma_parameter"], ["gamma_parameter + 1"])
```
Indeed, there are known function names in the ExprTK library and `gamma` is one of them. Hence, it cannot be chosen as a variable name. This fact is unclear in the error message:

https://github.com/openturns/openturns/blob/3bccfbf627c465daaf2ee3180c39d1e35012446c/lib/src/Base/Func/SymbolicParserExprTk.cxx#L232

The problem is not the variable: it is its _name_. The error should suggest to use a different name because this one is reserved by ExprTK and cannot be used.

### How to reproduce the issue?

```python
import openturns as ot
full_function = ot.SymbolicFunction(["gamma"], ["gamma + 1"])
full_function([0.0])
```

### Version

1.23

### Operating System

unknown

### Installation media

unknown

**Comment by ArashPartow** [comment]
Gamma is not an ExprTk keyword/reserved, the actual issue here is that the symbol name `gamma` is already defined to be a function and registered with the smybol_table: 

https://github.com/openturns/openturns/blob/3bccfbf627c465daaf2ee3180c39d1e35012446c/lib/src/Base/Func/SymbolicParserExprTk.cxx#L223

When the method symbol_table.add_variable is called it return false, because the symbol already exists.

A better why would be to initially check if the symbol already exists, then to call add_variable:

```
   if (symbol_table.symbol_exists(inputVariablesNames_[inputIndex],))
   {

      throw InvalidArgumentException(HERE) 
         << "Input variable: '" << inputVariablesNames_[inputIndex] 
         << "' at index: " << inputIndex << "already exists in symbol table";
   }
```
